on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: contraconreg1.azurecr.io
        username: ${{ secrets.acr_contraconreg1_username }}
        password: ${{ secrets.acr_contraconreg1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t contraconreg1.azurecr.io/aksc1:${{ github.sha }}
        docker push contraconreg1.azurecr.io/aksc1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksc1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksc1be30 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksc1be30`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksc1be30
        container-registry-url: contraconreg1.azurecr.io
        container-registry-username: ${{ secrets.acr_contraconreg1_username }}
        container-registry-password: ${{ secrets.acr_contraconreg1_password }}
        secret-name: aksc1dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aksc1be30
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          contraconreg1.azurecr.io/aksc1:${{ github.sha }}
        imagepullsecrets: |
          aksc1dockerauth